version: 2.1

orbs:
  allure: ayte/allure@0.1.3

jobs:
  build:
    docker:
      - image: circleci/node:dubnium-buster-browsers-legacy # Image that supports browser automation using JS
    resource_class: small # Specifying the size of the instance that is needed to run the tests
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          keys:
            - node_modules-{{ checksum "ui-tests/package.json" }}
            - node_modules- # fallback to using the latest cache if no exact match is found
      - run:
          name: "Install dependencies"
          command: |
            cd ui-tests
            npm install
      - save_cache:
          paths:
            - node_modules
          key: node_modules-{{ checksum "ui-tests/package.json" }}
      - run:
          name: "Check ESlinter Validation"
          command: |
            cd ui-tests
            npm run lint
